# Generated by Django 4.1.1 on 2023-03-23 03:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('CURP', models.CharField(max_length=18, unique=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('puntos', models.IntegerField(blank=True, default=0, null=True)),
                ('pic', models.ImageField(default='unknown.jpg', upload_to='')),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Tercera Edad', 'Tercera Edad'), ('Embarazadas', 'Embarazadas')], default='Normal', max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('admin', 'Funciones admin'), ('recolector', 'Funciones recolector'), ('canjeador', 'Funciones canjeador')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descuentos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DispoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('puntoskg', models.IntegerField(default=1)),
                ('preciokg', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('valor', models.DecimalField(decimal_places=1, default=1.0, max_digits=10)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PuntosReciclaje',
            fields=[
                ('nombre', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('direccion', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reciclaje.puntosreciclaje')),
                ('trbajador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Premio_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canjeado', models.BooleanField(default=False)),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciclaje.premio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.CharField(default=' ', max_length=40)),
                ('lugar', models.CharField(default=' ', max_length=40)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('Cantidad', models.FloatField(default=0)),
                ('puntos', models.FloatField(default=0)),
                ('Curp', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('DF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciclaje.dispofinal')),
            ],
        ),
    ]
