# Generated by Django 4.1.1 on 2022-10-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clave', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
