# Generated by Django 4.1.1 on 2022-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0005_user_pic_alter_dispofinal_preciokg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Tercera Edad', 'Tercera Edad'), ('Embarazadas', 'Embarazadas')], default='Normal', max_length=12),
        ),
    ]
