# Generated by Django 4.1.1 on 2022-11-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0006_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='valor',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
    ]
