# Generated by Django 4.1.1 on 2022-11-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0007_alter_premio_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('admin', 'Funciones admin'),)},
        ),
    ]
