# Generated by Django 4.1.1 on 2022-11-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0008_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
