# Generated by Django 4.1.1 on 2022-12-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0009_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosReciclaje',
            fields=[
                ('nombre', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('direccion', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('admin', 'Funciones admin'), ('recolector', 'Funciones recolector'), ('canjeador', 'Funciones canjeador'))},
        ),
        migrations.AddField(
            model_name='entradas',
            name='Cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entradas',
            name='Curp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entradas',
            name='puntos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='lugar',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='premio',
            name='valor',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=8),
        ),
    ]
