# Generated by Django 4.1.1 on 2022-12-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0011_dispofinal_id_entradas_id_alter_dispofinal_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispofinal',
            name='preciokg',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='premio',
            name='valor',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
    ]
