# Generated by Django 4.1.1 on 2022-12-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0011_dispofinal_id_entradas_id_alter_dispofinal_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispofinal',
            name='preciokg',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='premio',
            name='valor',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reciclaje.puntosreciclaje')),
                ('trbajador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
