# Generated by Django 4.1.1 on 2023-01-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0012_alter_dispofinal_preciokg_alter_premio_valor'),
        ('reciclaje', '0012_alter_dispofinal_preciokg_alter_premio_valor_and_more'),
    ]

    operations = [
    ]
