# Generated by Django 4.1.1 on 2023-01-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0013_merge_20230127_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='trabajador',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
